### ISSUE TITLE
Python adaptation - cross advertising?

### ISSUE THREAD

**Issue by Zethson** [neurorestore/Augur#15]
Hi,

we will finish a Python implementation of Augur for the Python & Scanpy ecosystem in January. I was wondering whether you would be up to cross advertising? We will of course link to the original R implementation and you could link to the Python implementation in your README or somewhere else.

Details from my side would follow.

**Comment by skinnider** [comment]
Hi @Zethson, very cool to hear, we would definitely be happy to point python users to your implementation if you can confirm the two implementations produce concordant results. There are some pre-processed datasets in our recent [Nature Protocols paper](https://www.nature.com/articles/s41596-021-00561-x) and associated [Zenodo repository](https://doi.org/10.5281/zenodo.4473025) that might be useful for this purpose.

**Comment by Zethson** [comment]
Glad to hear!
CC @antschum.

I'll keep you posted.

**Comment by Zethson** [comment]
@skinnider do you have a comment?

**Comment by skinnider** [comment]
Hi @Zethson, so sorry, somehow we must have missed this! Very cool to see the implementation is finished. I will add a link to your implementation in the README now.

**Comment by Zethson** [comment]
Thank you!
