### ISSUE TITLE
Public datasets in Seurat objects

### ISSUE THREAD

**Issue by zhangzehao626** [neurorestore/Augur#9]
Hi, 

Thank you for providing this powerful tool! I would like to test Augur with the publicly available data used in the paper. I noticed in Issue #1 that you were working on assembling all of the preprocessed, public datasets in a single repository of Seurat objects (not those were provided directly by the authors). Could you please inform me whether this repo still being developed? 

Thank you in advance!

**Comment by jordansquair** [comment]
You can access the repository here: https://doi.org/10.5281/zenodo.4772064

**Comment by zhangzehao626** [comment]
Thank you so much!
